insert into food (code, name, some_value, kcal, kj, water, dietary_fiber, carbohydrates, proteins, total_lipids, saturated_lipids, monosaturated_lipids, polysaturated_lipids, cholesterol, calcium, phosphorus, iron, magnesium, sodium, potassium, zinc, vitamin_a, ascorbic_acid, thiamin, riboflavin, niacin, pyridoxine, folic_acid, cobalamin, edible_percentage, one, two, three) VALUES ('AYM-1','Azúcar morena',NULL,380,1590,7.4,0,98.09,0.12,0,0,0,0,0,51,NULL,0.71,NULL,1,3,0.03,0,0,0.02,0.11,0.3,NULL,NULL,0,100,NULL,14,7);
insert into food (code, name, some_value, kcal, kj, water, dietary_fiber, carbohydrates, proteins, total_lipids, saturated_lipids, monosaturated_lipids, polysaturated_lipids, cholesterol, calcium, phosphorus, iron, magnesium, sodium, potassium, zinc, vitamin_a, ascorbic_acid, thiamin, riboflavin, niacin, pyridoxine, folic_acid, cobalamin, edible_percentage, one, two, three) VALUES ('AYM-2','Azúcar refinada (estándar)',NULL,396,1659,0.5,0,99.1,0,0,0,0,0,0,0,0,0,0,NULL,NULL,0,0,0,0,0,NULL,NULL,NULL,0,100,NULL,14,7);
insert into food (code, name, some_value, kcal, kj, water, dietary_fiber, carbohydrates, proteins, total_lipids, saturated_lipids, monosaturated_lipids, polysaturated_lipids, cholesterol, calcium, phosphorus, iron, magnesium, sodium, potassium, zinc, vitamin_a, ascorbic_acid, thiamin, riboflavin, niacin, pyridoxine, folic_acid, cobalamin, edible_percentage, one, two, three) VALUES ('AYM-3','Jarabe de maple',NULL,260,1088,33,0,65,0,0,0,0,0,0,104,NULL,1.2,NULL,10,176,NULL,0,0,0,0,0,0,0,0,100,NULL,14,7);
insert into food (code, name, some_value, kcal, kj, water, dietary_fiber, carbohydrates, proteins, total_lipids, saturated_lipids, monosaturated_lipids, polysaturated_lipids, cholesterol, calcium, phosphorus, iron, magnesium, sodium, potassium, zinc, vitamin_a, ascorbic_acid, thiamin, riboflavin, niacin, pyridoxine, folic_acid, cobalamin, edible_percentage, one, two, three) VALUES ('AYM-4','Jarabe sabor a maple',NULL,288,1205,28,0,72,0,0,0,0,0,0,0,NULL,0,NULL,NULL,0,0,0,0,0,0,0,0,0,0,100,NULL,14,7);
insert into food (code, name, some_value, kcal, kj, water, dietary_fiber, carbohydrates, proteins, total_lipids, saturated_lipids, monosaturated_lipids, polysaturated_lipids, cholesterol, calcium, phosphorus, iron, magnesium, sodium, potassium, zinc, vitamin_a, ascorbic_acid, thiamin, riboflavin, niacin, pyridoxine, folic_acid, cobalamin, edible_percentage, one, two, three) VALUES ('AYM-5','Melaza',NULL,285,1192,25.9,0,71,0,0.1,0,0,0,0,380,93,8.8,NULL,49,1636,NULL,0,0,0.41,0.12,1.13,0,0,0,100,NULL,14,7);
insert into food (code, name, some_value, kcal, kj, water, dietary_fiber, carbohydrates, proteins, total_lipids, saturated_lipids, monosaturated_lipids, polysaturated_lipids, cholesterol, calcium, phosphorus, iron, magnesium, sodium, potassium, zinc, vitamin_a, ascorbic_acid, thiamin, riboflavin, niacin, pyridoxine, folic_acid, cobalamin, edible_percentage, one, two, three) VALUES ('AYM-6','Miel de abeja',NULL,304,1272,17.2,0,82.4,0.3,0,0,0,0,0,20,16,0.42,3,5,51,0.22,0,0.5,0.01,0.07,0.2,NULL,NULL,0,100,NULL,14,7);
insert into food (code, name, some_value, kcal, kj, water, dietary_fiber, carbohydrates, proteins, total_lipids, saturated_lipids, monosaturated_lipids, polysaturated_lipids, cholesterol, calcium, phosphorus, iron, magnesium, sodium, potassium, zinc, vitamin_a, ascorbic_acid, thiamin, riboflavin, niacin, pyridoxine, folic_acid, cobalamin, edible_percentage, one, two, three) VALUES ('AYM-7','Miel de caña',NULL,294,1231,25.6,0,72.6,0.5,0.2,0,0,0,0,70,42,1.2,NULL,NULL,425,NULL,0,3,0.02,0.06,0.4,NULL,NULL,0,100,NULL,14,7);
insert into food (code, name, some_value, kcal, kj, water, dietary_fiber, carbohydrates, proteins, total_lipids, saturated_lipids, monosaturated_lipids, polysaturated_lipids, cholesterol, calcium, phosphorus, iron, magnesium, sodium, potassium, zinc, vitamin_a, ascorbic_acid, thiamin, riboflavin, niacin, pyridoxine, folic_acid, cobalamin, edible_percentage, one, two, three) VALUES ('AYM-8','Miel de maíz',NULL,300,1255,24,0,75,0,0,0,0,0,0,46,NULL,4.1,NULL,68,4,NULL,0,0,0,0,0,0,0,0,100,NULL,14,7);
insert into food (code, name, some_value, kcal, kj, water, dietary_fiber, carbohydrates, proteins, total_lipids, saturated_lipids, monosaturated_lipids, polysaturated_lipids, cholesterol, calcium, phosphorus, iron, magnesium, sodium, potassium, zinc, vitamin_a, ascorbic_acid, thiamin, riboflavin, niacin, pyridoxine, folic_acid, cobalamin, edible_percentage, one, two, three) VALUES ('AYM-9','Piloncillo',NULL,362,1516,7.4,0,90.6,0,0,0,0,0,0,51,44,4.2,NULL,30,344,NULL,1.5,2,0.02,0.11,0.3,NULL,NULL,0,100,NULL,14,7);
